spring.application.name=backend


project.image = images/

spring.security.user.password=${ADMIN_PASSWORD}
spring.security.user.name=${ADMIN_USERNAME}

# spring.datasource.url=jdbc:h2:mem:test
# spring.h2.console.enabled=true

spring.sql.init.mode=always

spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
spring.app.jwtCookieName=${JWT_COOKIE_NAME}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.e_comerce.backend=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

momo.partner-code=${MOMO_PARTNER_CODE}
momo.access-key=${MOMO_ACCESS_KEY}
momo.secret-key=${MOMO_SECRET_KEY}
momo.endpoint-create=${MOMO_API_ENDPOINT}/create
momo.redirect-url=${MOMO_REDIRECT_URL}
momo.ipn-url=${MOMO_IPN_URL}
momo.request-type=captureWallet